[package]
name = "fconv"
version = "0.7.1"
edition = "2021"
description = "Data format converter"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.11", features = ["derive"] }
indexmap = "2.0.0"
plist = "1.4.3"
serde = "1.0.167"
serde-pickle = "1.1.1"
serde_json = "1.0.100"
serde_yaml = "0.9.22"
toml = "0.7.6"

[dev-dependencies]
serde_test = "1.0.167"

[profile.release]
codegen-units = 1
lto = true
strip = true
