[package]
name = "fconv"
version = "0.2.0"
edition = "2021"
description = "Data format converter"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "2.33.3", features = ["yaml"]}
linked-hash-map = "0.5.4"
serde = "1.0.130"
serde-pickle = "1.1.0"
serde_json = "1.0.68"
serde_test = "1.0.130"
serde_yaml = "0.8.21"
toml = "0.5.8"
