[package]
name = "fconv"
version = "0.7.0"
edition = "2021"
description = "Data format converter"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
indexmap = "1.9.1"
plist = "1.3.1"
serde = "1.0.142"
serde-pickle = "1.1.1"
serde_json = "1.0.83"
serde_yaml = "0.9.4"
toml = "0.5.9"

[dev-dependencies]
serde_test = "1.0.142"

[profile.release]
codegen-units = 1
lto = true
strip = true
