[package]
name = "fconv"
version = "0.5.0"
edition = "2021"
description = "Data format converter"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.16", features = ["derive"] }
linked-hash-map = "0.5.4"
plist = "1.3.1"
serde = "1.0.137"
serde-pickle = "1.1.1"
serde_json = "1.0.81"
serde_yaml = "0.8.26"
toml = "0.5.9"

[dev-dependencies]
serde_test = "1.0.142"
